### ISSUE TITLE
Replace dependency

### ISSUE THREAD

**Issue by klettier** [arolla/FormationWebApi#3]
Replace

https://github.com/arolla/FormationWebApi/blob/2ecd935ddb78427fb83e7bd5612bb26465d287ff/Owin/src/Bookings.Hosting/Bookings.Hosting.csproj#L10

By

```<PackageReference Include="Microsoft.AspNet.WebApi.WebHost" Version="5.2.6" />```

**Comment by bhugot** [comment]
It s replaced in second branch

**Comment by klettier** [comment]
The second branch has it too, the dependencies should be 

```
    <PackageReference Include="Microsoft.AspNet.WebApi.OwinSelfHost" Version="5.2.6" />
    <PackageReference Include="Microsoft.AspNet.WebApi.WebHost" Version="5.2.6" />
    <PackageReference Include="Swashbuckle" Version="5.6.0" />
```

and not

```
    <PackageReference Include="Microsoft.AspNet.WebApi.OwinSelfHost" Version="5.2.6" />
    <PackageReference Include="Microsoft.AspNet.WebApi.WebHost" Version="5.2.6" />
    <PackageReference Include="Microsoft.Owin.SelfHost" Version="4.0.0" />
    <PackageReference Include="Swashbuckle" Version="5.6.0" />
```

https://github.com/arolla/FormationWebApi/blob/2-swagger/Owin/src/Bookings.Hosting/Bookings.Hosting.csproj#L11 can be removed
